# Site settings
title: Taskalito
email: office@taskalito.com
description: > # this means to ignore newlines until "baseurl:"
  Taskalito is a mobile app that lets users create task reminders from images. Compared to other productivity apps, it is focused on images and less typing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
apple_link: https://itunes.apple.com/us/app/taskalito/id977642411?mt=8
exclude:
  - node_modules
